export const TOKENS = {
    "+": { type: "PLUS", rep: "{+}" },
    "-": { type: "MINUS", rep: "{-}" },
    "*": { type: "MULTIPLY", rep: "{\\times}" },
    "/": { type: "DIVIDE", rep: "{\\div}" },
    "^": { type: "POWER", rep: "^\\wedge" },
    "(": { type: "LPAREN", rep: "(" },
    ")": { type: "RPAREN", rep: ")" },
    "!": { type: "FACTORIAL", rep: "!" },
    "%": { type: "PERCENT", rep: "\\%" },
    ",": { type: "COMMA", rep: "," },
    "P": { type: "PERMUTATION", rep: "P" },
    "C": { type: "COMBINATION", rep: "C" },
    "r": { type: "RADIANS", rep: "{^\\mathrm{r}}" },
    "g": { type: "GRADIANS", rep: "{^\\mathrm{g}}" },
    "d": { type: "DEGREES", rep: "{^\\circ}" },
    "p": { type: "CONSTANT", exp: "PI", rep: "{\\pi}" },
    "e": { type: "CONSTANT", exp: "E", rep: "{e}" },
    "E": { type: "DIGIT", rep: "{\\footnotesize\\times{\\texttt{10}}}"},
    ".": { type: "DIGIT", rep: "."},
    "s": { type: "FUNCTION", exp: "SIN", rep: "\\sin("},
    "c": { type: "FUNCTION", exp: "COS", rep: "\\cos("},
    "t": { type: "FUNCTION", exp: "TAN", rep: "\\tan("}
}